### ISSUE TITLE
object scala in compiler mirror not found

### ISSUE THREAD

**Issue by ewsmith** [coolsquid/SquidScript#5]
any time i have code that isn't a comment i get this error
[http://pastebin.com/Fr2hgPnt](http://pastebin.com/Fr2hgPnt)

1.0.9b and 1.0.9c crash while 1.0.8 just errors
i'm running archlinux x64 and can use both java 7 and 8 (both x64)

**Comment by coolsquid** [comment]
o.O

No idea why that happens. Are you using OpenJDK?

**Comment by ewsmith** [comment]
Yes. OpenJDK7 and OpenJDK8.

I was going to download and install the oracle version to test, but they took this moment to have an 'unscheduled outage' with their cdn. :/

**Comment by ewsmith** [comment]
I've install oracle's jre8 and get the same crash. :c

**Comment by ewsmith** [comment]
the crash also happens on windows 7 x64 with jre8
it still happens when it's the only mod installed

it doesn't crash with the official launcher but it still errors
[http://pastebin.com/70NxCMQc](http://pastebin.com/70NxCMQc)

**Comment by coolsquid** [comment]
I can't reproduce it. No idea why it happens :/

**Comment by ewsmith** [comment]
it must be related to my computer setup
i'm considering get a new computer Soon™
so, i'll close this and just tell you if i manage to figure out what it is
